### ISSUE TITLE
error on every command 

### ISSUE THREAD

**Issue by acerphoenix** [akuma/evermark#26]
⬢  ~  evermark help
/usr/local/lib/node_modules/evermark/bin/cli.js:24
const { Evermark, config } = require(DEV ? '../src' : '../lib')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3

nomatter i write any command. this is the only output. my os is MacOS 10.12

**Comment by akuma** [comment]
Hi, what's your node version?
Evermark now only support Node >= v6

**Comment by acerphoenix** [comment]
耶，发现都是国人咱就母语啦。
果然我升到node6.4就不再报错了，init 一个目录之后，应该是成功了。INFO  Evermark folder has been initialized.但是，在执行后续任何命令，会报这个错。ERROR  Please run `evermark init [destination]` to init a new Evermark folder
我不太了解init一个目录干嘛用。我选了随便一个目录，也选过我实际md文件所在的目录，都不行

**Comment by akuma** [comment]
你执行 `evermark init` 的时候，命令行会让你进行如下操作：

1. 选择你用的是 Evernote 还是 印象笔记？
2. 输入你的 Developer Token。

这些你都设置正常了吗？你可以通过查看 `evermark.json` 文件确认，内容类似这样：

```json
{
  "token": "...",
  "china": true,
  "highlight": "gruvbox-dark"
}
```

然后确保你执行每个 evermark 命令的时候，处于 `evermark.json` 文件所在的目录，这个是 evermark 的根目录。

**Comment by acerphoenix** [comment]
看来我就是执行后续命令时，没有处于`evermark.json`所在的根目录。 等上班试试去，多谢

**Comment by akuma** [comment]
嗯，有问题再说好了。

**Comment by acerphoenix** [comment]
有，这东西真不错，我typora写，自动发布到evernote，方便其他平台，尤其是手机平台看。
但，publish时，能选笔记本不？evernote api应该有提供，还有，发布md文件，对应到笔记名称，无法自己指定，默认都md文件名作为笔记名称是不是好点？

**Comment by akuma** [comment]
我用一个简单的例子来说明：

```markdown
# Hello World                              ---- 笔记名称，以内容中出现的第一个标题命名

@(测试)[hello|world]                       ---- “测试” 是所属笔记本，“hello” 和 “world” 是笔记的标签

你好，世界！
```

如果你用 `evermark new` 命令创建的 md 文件，那么默认的笔记名称和文件名是一致的。

看看这些是否满足你的需求。

**Comment by acerphoenix** [comment]
evermark publish xxx.md @(note) 就发布到note本了？

**Comment by akuma** [comment]
你理解错了，我上面的例子是一个 markdown 笔记的内容。

**Comment by acerphoenix** [comment]
哦，笔记内容里得写@(notebook)才能指定笔记本？

**Comment by akuma** [comment]
是的

**Comment by akuma** [comment]
如果没有问题这个 issue 就关闭了。

**Comment by acerphoenix** [comment]
好的，暂时没了。多谢
