### ISSUE TITLE
能否开一个赞助链接？

### ISSUE THREAD

**Issue by TooSchoolForCool** [akuma/evermark#63]
非常喜欢这个项目，给予了我很多的便利。

之前都是使用马克飞象来完成evernote的同步，一来马克飞象每年都有订阅的费用，其次编辑的体验和渲染都不如typora。

Evermark终于实现了我一直以来的期望，typora的本地编辑 + evernote的同步。

非常感谢作者能够开源这个项目，希望能够开通一个赞助的方式。

一个穷学生，可能赞助不了多少钱，但是还是想表达一下心意。

也相信会有和我一样想法的人，借此能表示下对作者的感谢。

**Comment by akuma** [comment]
第一次在 GitHub 上收到别人热情的感谢，我很感动。
因为工作比较忙，这个项目已经很久没更新了，其实还有很多地方值得改进。
不过能够因为自己的一点点工作而帮助到你，我还是很高兴的。
欢迎对这个工具提建议，谢谢你！

**Comment by akuma** [comment]
已在首页添加赞助信息。

**Comment by TooSchoolForCool** [comment]
:)

昨晚上试用了一下，总体感觉还是很不错的。

不过有一点问题的是note的默认存放路径是notes/，如果笔记存放到别的路径的时候load image的时候会出bug。笔记里面load image用的是相对路径，但是evermark处理的时候会以notes/作为当前工作路径，导致索引不到图片。

**Comment by akuma** [comment]
谢谢赞赏及反馈，我会修改一下。
